# Generated by Django 5.2.4 on 2025-07-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='obj_type',
            new_name='objType',
        ),
        migrations.RenameField(
            model_name='taskrequirement',
            old_name='req_task_id',
            new_name='reqTaskId',
        ),
        migrations.AlterField(
            model_name='taskrequirement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskRequirements', to='api.task'),
        ),
    ]
