services:
  backend:
    image: mark1qaz/backend:latest
    build:
      context: backend
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./most_recent_items.json:/ItemsApp/most_recent_items.json
      - ./most_recent_tasks.json:/ItemsApp/most_recent_tasks.json
    depends_on:
      - db
      - redis

  frontend:
    image: mark1qaz/frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - mark1qaz/frontend:buildcache
      cache_to:
        - mark1qaz/frontend:buildcache
    expose:
      - "3000"
    volumes:
      - ./icons:/ItemsApp/public:ro
    environment:
      - HOSTNAME=0.0.0.0
      - CHOKIDAR_USEPOLLING=false
      - NEXT_PUBLIC_BASE_PATH=
      - NEXT_PUBLIC_BACKEND_SERVER=http://backend:8000
    restart: unless-stopped

  nginx:
    container_name: "nginx"
    image: nginx:stable-alpine3.21-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./${FULLCHAIN_KEY}:/etc/ssl/certs/fullchain.pem
      - ./${DOMAIN_PRIVKEY}:/etc/ssl/private/privkey.pem
    command: ["nginx", "-g", "daemon off;"]

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    command: ["redis-server", "--save", "", "--appendonly", "no", "--hz", "1"]
    restart: unless-stopped
    expose:
      - "6379"

volumes:
  pgdata:
