services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/ItemsApp
    ports:
      - "8000:8000"
    depends_on:
      - db
    #command: ["sh", "wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - POSTGRES_DB=items
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
      context: .
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/ItemsApp
      - /ItemsApp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: items
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: