services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    command: ["redis-server", "--save", "", "--appendonly", "no", "--hz", "1"]
    #image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1
    #command:
    #  ["dragonfly", "--dbfilename=", "", "--cache_mode", "true", "--hz", "1"]
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  pgdata:
