services:
  backend:
    container_name: "backend-dev"

  frontend:
    container_name: "frontend-dev"
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/ItemsApp
      - /ItemsApp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
