services:
  backend:
    image: mark1qaz/backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
      cache_from:
        - mark1qaz/backend:buildcache
      cache_to:
        - mark1qaz/backend:buildcache
    environment:
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=False
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis

  frontend:
    image: mark1qaz/frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - mark1qaz/frontend:buildcache
      cache_to:
        - mark1qaz/frontend:buildcache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./icons:/usr/share/nginx/html/icons:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./${FULLCHAIN_KEY}:/etc/ssl/certs/fullchain.pem
      - ./${DOMAIN_PRIVKEY}:/etc/ssl/private/privkey.pem
    environment:
      - CHOKIDAR_USEPOLLING=false
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    expose: 
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    command: ["redis-server", "--save", "", "--appendonly", "no", "--hz", "1"]
    restart: unless-stopped
    expose: 
      - "6379"

volumes:
  pgdata:
