services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/ItemsApp
    ports:
      - "8000:8000"
  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
      context: .
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/ItemsApp
      - /ItemsApp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true