services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/ItemsApp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
      context: .
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/ItemsApp
      - /ItemsApp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_SERVER=${VITE_BACKEND_SERVER}

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.22
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
