# Generated by Django 5.2.3 on 2025-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_id',
            field=models.CharField(db_index=True, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='avg24hPrice',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='basePrice',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='changeLast48hPercent',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='shortName',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellfor',
            name='price',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sellfor',
            name='source',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
