# Generated by Django 5.2.3 on 2025-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item__id_alter_item_avg24hprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='avg24hPrice',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='basePrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='changeLast48hPercent',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='shortName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellfor',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
