# Generated by Django 5.2.3 on 2025-07-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_avg24hprice_alter_item_baseprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellfor',
            name='price',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
