# Generated by Django 5.2.3 on 2025-06-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=50)),
                ('avg24hPrice', models.IntegerField(default=0, null=True)),
                ('basePrice', models.IntegerField(default=0)),
                ('changeLast48hPercent', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='websiteApi.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(blank=True, to='websiteApi.types'),
        ),
    ]
