on:
  push:
    branches: ["main"]

jobs:
  itemsapp-docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3

      - name: build prod docker container
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml build

      - name: start prod docker container
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d

      - name: wait for backend to be healthy
        run: |
          until curl -s http://localhost:8000/health; do
            sleep 2
          done

      - name: run pytest tests
        run: docker exec backend pytest api/tests.py

      - name: install locust
        run: pip install locust

      - name: run backend locust tests
        run: locust -f locust_testing_backend.py --headless -u 10 -r 1 --run-time 30s --fail-on-failure

      - name: run frontend locust tests
        run: locust -f locust_testing_frontend.py --headless -u 10 -r 1 --run-time 30s --fail-on-failure
