on:
  push:
    branches: ["main"]

jobs:
  itemsapp-docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3

      - name: build prod docker container
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml build

      # - name: start prod docker container
      #   run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d --wait backend

      - name: wait for backend to be healthy
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml run --rm backend sh -c 'until curl -s http://localhost:8000/health; do sleep 2; done'

      - name: run pytest tests
        run: docker exec backend pytest api/tests.py
