on:
  push:
    branches: ["main"]

jobs:
  itemsapp-docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3

      - name: cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: build backend with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: backend
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: build frontend with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: false
          tags: frontend
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: build prod docker container
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml build

      - name: start prod docker container
        run: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d

      - name: wait for backend to be healthy
        run: |
          until curl -s http://localhost:8000/health; do
            sleep 2
          done

      - name: run pytest tests
        run: docker exec backend pytest api/tests.py

      - name: install locust
        run: pip install locust

      - name: run backend locust tests
        run: locust -f locust_testing_backend.py --headless -u 10 -r 1 --run-time 30s

      - name: run frontend locust tests
        run: locust -f locust_testing_frontend.py --headless -u 10 -r 1 --run-time 30s
